### ISSUE TITLE
Server function to fetch interval of historical records

### ISSUE THREAD

**Issue by PhilippSteinmann** [Zabari/STEPS#13]
For example, 100 records that are 300 records removed from the most recent one.

**Comment by afischer** [comment]
Can you elaborate? I'm confused.

**Comment by PhilippSteinmann** [comment]
Functions: 
- `fetchHistoryInterval(str escalator, int min=0, int max=100)`
  - Returns (max-min) statuses & times for that specific escalator
- `fetchHistoryIntervalAll(str escalator, int min=0, int max=100)`
  - Returns (max-min) statuses & times for all escalators

For getting a specific part of history.

**Comment by trunkatedpig** [comment]
That would be useful, and it would probably be easier to do in SQL than in
js/python.

On Fri, Jan 23, 2015 at 12:00 PM, PhilippSteinmann <notifications@github.com

**Comment by PhilippSteinmann** [comment]
Yep, Zabari's working on it.
