### ISSUE TITLE
Queries to /newdata constant across pages

### ISSUE THREAD

**Issue by afischer** [Zabari/STEPS#3]
Do we need to query /newData even if the user isn't currently looking at the web page?

**Comment by PhilippSteinmann** [comment]
I think we should decrease the query frequency (to, like, 10 seconds).
Somehow I don't feel so confident stopping all querying. But slowing the querying will probably decrease server load.

**Comment by afischer** [comment]
Yeah I'm just worried that if like 200 people are looking at in a tab in the background and not all of them are on the main page, it's just going to murder our server
