### ISSUE TITLE
Escalator Data Grabber fails for double digit escalator numbers

### ISSUE THREAD

**Issue by afischer** [Zabari/STEPS#4]
e1,e2,v1,v2 = int(s[1]), int(s[7]), int(s[4]), int(s[10]) won't actually work for any of the double digit numbered escalators.

Check out if you can fix this?

**Comment by trunkatedpig** [comment]
will do. Any idea why what was there before was breaking? Because I'm not
sure how else to fix this...

**Comment by Zabari** [comment]
What if you just put them on seperate lines

**Comment by trunkatedpig** [comment]
don't be ridiculous I don't even know what separate lines are

**Comment by afischer** [comment]
![reallytho](http://i.telegraph.co.uk/multimedia/archive/02536/george-bush-3_2536602b.jpg)

**Comment by trunkatedpig** [comment]
​

**Comment by trunkatedpig** [comment]
Last commit should fix it; can't test without the raspberry pi but 95% sure it will work.
